import { readFileSync, writeFileSync } from "node:fs"
import { pathToFileURL } from "node:url"

// Phase 2 of the functional-correctness proof pipeline.
//
// Reads the EntryPoint-computed operation hashes emitted by
// script/proof/DumpUserOpHashes.s.sol and produces genuine Semaphore v4 / Groth16
// proofs whose `message` is one of those hashes. Phase 3
// (test/FunctionalCorrectness.t.sol) asserts the hashes still match before submitting.
//
// Every proof here is produced by snarkjs `groth16.fullProve` against the published
// Semaphore trusted-setup artifacts and is checked with `verifyProof` before being written.

const corePath = process.env.SEMAPHORE_CORE_PATH ?? "@semaphore-protocol/core"
const coreModule = corePath.startsWith("/") ? pathToFileURL(corePath).href : corePath
const { Identity, Group, generateProof, verifyProof } = await import(coreModule)

const ops = JSON.parse(readFileSync("test/fixtures/functional-correctness-ops.json", "utf8"))

const scope = BigInt(ops.scope)
const groupSize = Number(ops.groupSize)

// Deterministic identities — the same private keys always regenerate the same group.
const identities = Array.from(
  { length: groupSize },
  (_, i) => new Identity(`privgas-functional-correctness-credit-${i}`)
)
const commitments = identities.map((id) => id.commitment)

// Insertion order here must match the on-chain CreditPool deposit order.
const group = new Group(commitments)

// The spending credit is a non-first leaf, so the Merkle path is not degenerate.
const SPENDER_INDEX = 1
const spender = identities[SPENDER_INDEX]

const merkleTreeDepth = 2 // 4 leaves -> 2 siblings

async function proveFor(label, userOpHashHex) {
  const message = BigInt(userOpHashHex)
  const proof = await generateProof(spender, group, message, scope, merkleTreeDepth)
  const ok = await verifyProof(proof)
  if (!ok) {
    throw new Error(`generated proof for ${label} failed off-chain verification`)
  }
  if (BigInt(proof.message) !== message) {
    throw new Error(`proof message mismatch for ${label}`)
  }
  if (BigInt(proof.merkleTreeRoot) !== group.root) {
    throw new Error(`proof root mismatch for ${label}`)
  }
  console.log(`  ${label}: verified, nullifier=${proof.nullifier}`)
  return proof
}

console.log("Generating genuine Groth16 proofs over EntryPoint-computed operation hashes:")
const accept = await proveFor("opAccept", ops.opAccept)
const second = await proveFor("opSecond", ops.opSecond)
const overBudget = await proveFor("opOverBudget", ops.opOverBudget)

// The scope is fixed, so one credit yields one nullifier across every operation.
// This is what makes the spent-nullifier case a genuine double-spend rather than
// two unrelated proofs.
if (accept.nullifier !== second.nullifier || accept.nullifier !== overBudget.nullifier) {
  throw new Error("expected a single credit-scoped nullifier across all proofs")
}

const fixture = {
  note: "Generated by script/proof/generateFunctionalCorrectnessProofs.mjs. Do not hand-edit.",
  groupSize,
  merkleTreeDepth,
  scope: scope.toString(),
  nullifier: accept.nullifier,
  spenderIndex: SPENDER_INDEX,
  commitments: commitments.map((c) => c.toString()),
  groupRoot: group.root.toString(),
  sourceOps: {
    opAccept: ops.opAccept,
    opSecond: ops.opSecond,
    opOtherSender: ops.opOtherSender,
    opOverBudget: ops.opOverBudget
  },
  proofs: { accept, second, overBudget },
  verified: true
}

writeFileSync(
  "test/fixtures/functional-correctness-proofs.json",
  `${JSON.stringify(fixture, null, 2)}\n`
)

console.log("Wrote test/fixtures/functional-correctness-proofs.json")
console.log(`  groupRoot: ${group.root}`)
console.log(`  nullifier: ${accept.nullifier}`)
